import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';

interface PDFExportOptions {
  filename: string;
  data: any;
  reportType: string;
}

export function generateProjectSummaryPDF(data: any, filename: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
        bufferPages: true,
        autoFirstPage: false
      });

      const chunks: Buffer[] = [];
      
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const { projects = [], milestones = [] } = data;

      let pageNumber = 0;
      
      const addNewPage = () => {
        doc.addPage();
        pageNumber++;
        addHeader();
        addFooter();
        return 130;
      };

      const addHeader = () => {
        const logoPath = path.join(__dirname, '../../Appkings.png');
        
        if (fs.existsSync(logoPath)) {
          doc.image(logoPath, 50, 40, { width: 50 });
        }

        doc.fontSize(20)
           .fillColor('#1F4E79')
           .font('Helvetica-Bold')
           .text('Project Summary Report', 120, 50, { align: 'left' });

        doc.fontSize(9)
           .fillColor('#666666')
           .font('Helvetica')
           .text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 120, 75, { align: 'left' });

        doc.moveTo(50, 105)
           .lineTo(545, 105)
           .strokeColor('#4472C4')
           .lineWidth(2)
           .stroke();
      };

      const addFooter = () => {
        doc.fontSize(8)
           .fillColor('#999999')
           .font('Helvetica')
           .text(
             `Page ${pageNumber} - Generated by TaskFlow System`,
             50,
             770,
             { align: 'center', width: 495 }
           );
      };

      let currentY = addNewPage();

      const totalProjects = projects.length;
      const activeProjects = projects.filter((p: any) => 
        p.Status !== 'completed' && p.Status !== 'cancelled'
      ).length;
      const completedProjects = projects.filter((p: any) => p.Status === 'completed').length;
      const avgProgress = totalProjects > 0 
        ? Math.round(projects.reduce((sum: number, p: any) => sum + (parseInt(p['Progress (%)']) || 0), 0) / totalProjects)
        : 0;

      doc.fontSize(10)
         .fillColor('#666666')
         .font('Helvetica')
         .text(`Total Projects: ${totalProjects} | Active: ${activeProjects} | Completed: ${completedProjects} | Avg Progress: ${avgProgress}%`, 50, currentY, { align: 'center', width: 495 });
      
      currentY += 25;

      const tableHeaderHeight = 30;
      const projectRowHeight = 28;
      const milestoneRowHeight = 26;
      
      doc.rect(50, currentY, 495, tableHeaderHeight)
         .fillAndStroke('#E8E8E8', '#AAAAAA')
         .lineWidth(1.5);

      doc.fillColor('#1a1a1a')
         .fontSize(9)
         .font('Helvetica-Bold')
         .text('Project / Milestone', 58, currentY + 10, { width: 132 });
      doc.text('Type', 195, currentY + 10, { width: 40, align: 'center' });
      doc.text('Status', 240, currentY + 10, { width: 45, align: 'center' });
      doc.text('Progress', 285, currentY + 10, { width: 33, align: 'center' });
      doc.text('Budget/Fee', 323, currentY + 10, { width: 52, align: 'right' });
      doc.text('Days', 380, currentY + 10, { width: 30, align: 'center' });
      doc.text('Start', 415, currentY + 10, { width: 38, align: 'center' });
      doc.text('End', 458, currentY + 10, { width: 38, align: 'center' });
      doc.text('Manager', 501, currentY + 10, { width: 39, align: 'center' });

      currentY += tableHeaderHeight;

      if (projects.length === 0) {
        doc.rect(50, currentY, 495, projectRowHeight)
           .fillAndStroke('#FFFFFF', '#E5E5E5')
           .lineWidth(0.5);
           
        doc.fontSize(10)
           .fillColor('#999999')
           .font('Helvetica-Oblique')
           .text('No projects available', 58, currentY + 10, { align: 'center', width: 485 });
           
        currentY += projectRowHeight;
      } else {
        const calculateDuration = (startDate: string, endDate: string): string => {
          if (!startDate || startDate === 'N/A' || !endDate || endDate === 'N/A') return '-';
          try {
            const start = new Date(startDate);
            const end = new Date(endDate);
            const diffTime = Math.abs(end.getTime() - start.getTime());
            const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
            return `${diffDays}d`;
          } catch {
            return '-';
          }
        };

        projects.forEach((project: any, projectIndex: number) => {
          const projectName = project['Project Name'];
          const projectMilestones = milestones.filter((m: any) => 
            m.Client === project['Client'] && m['_projectName'] === projectName
          );
          
          if (currentY + projectRowHeight > 720) {
            currentY = addNewPage();
          }

          const projectBg = '#F8F9FA';
          doc.rect(50, currentY, 495, projectRowHeight)
             .fillAndStroke(projectBg, '#D0D0D0')
             .lineWidth(1);

          doc.fillColor('#000000')
             .fontSize(9)
             .font('Helvetica-Bold')
             .text(project['Project Name'], 58, currentY + 10, { width: 132, ellipsis: true });

          doc.fillColor('#666666')
             .fontSize(8)
             .font('Helvetica-Bold')
             .text('PROJECT', 195, currentY + 10, { width: 40, align: 'center' });

          doc.fillColor('#444444')
             .fontSize(8)
             .font('Helvetica')
             .text(project.Status ? project.Status.toUpperCase() : 'N/A', 240, currentY + 10, { width: 45, align: 'center' });
          
          const projectProgress = project['Progress (%)'];
          const progressValue = projectProgress !== undefined && projectProgress !== null ? Math.round(projectProgress) : 0;
          doc.text(`${progressValue}%`, 285, currentY + 10, { width: 33, align: 'center' });
          
          const budget = project['Budget (KSh)'] || '0';
          const budgetNum = typeof budget === 'string' ? parseFloat(budget.replace(/,/g, '')) : budget;
          doc.text(budgetNum ? budgetNum.toLocaleString() : '0', 323, currentY + 10, { width: 52, align: 'right' });
          
          const duration = calculateDuration(project['Start Date'], project['End Date']);
          doc.text(duration, 380, currentY + 10, { width: 30, align: 'center' });
          doc.text(project['Start Date'] || 'N/A', 415, currentY + 10, { width: 38, align: 'center' });
          doc.text(project['End Date'] || 'N/A', 458, currentY + 10, { width: 38, align: 'center' });
          doc.text(project.Manager || 'N/A', 501, currentY + 10, { width: 39, ellipsis: true });

          currentY += projectRowHeight;

          if (projectMilestones.length > 0) {
            projectMilestones.forEach((milestone: any, mIndex: number) => {
              if (currentY + milestoneRowHeight > 720) {
                currentY = addNewPage();
              }

              const milestoneBg = mIndex % 2 === 0 ? '#FFFFFF' : '#F8F8F8';
              doc.rect(50, currentY, 495, milestoneRowHeight)
                 .fillAndStroke(milestoneBg, '#DDDDDD')
                 .lineWidth(0.5);

              const statusColors: Record<string, string> = {
                'done': '#28A745',
                'finished': '#28A745',
                'completed': '#28A745',
                'in_progress': '#4472C4',
                'ongoing': '#4472C4',
                'fc_review': '#4472C4',
                'started': '#FFA500',
                'overdue': '#DC3545',
                'delayed': '#DC3545',
                'on_hold': '#6C757D',
                'cancelled': '#6C757D',
                'todo': '#999999',
                'not started': '#999999',
                'not_started': '#999999'
              };

              const milestoneStatus = (milestone.Status || 'not_started').toLowerCase().replace(/ /g, '_');
              const statusColor = statusColors[milestoneStatus] || '#999999';

              doc.fontSize(10)
                 .fillColor(statusColor)
                 .font('Helvetica')
                 .text('●', 63, currentY + 9);

              doc.fillColor('#2C2C2C')
                 .fontSize(8)
                 .font('Helvetica')
                 .text(milestone['Milestone Name'], 73, currentY + 9, { width: 117, ellipsis: true });

              doc.fillColor('#777777')
                 .fontSize(7)
                 .text('Milestone', 195, currentY + 9, { width: 40, align: 'center' });
              
              doc.fillColor('#555555')
                 .fontSize(8)
                 .text(milestone.Status || 'not_started', 240, currentY + 9, { width: 45, align: 'center' });
              
              const milestoneProgress = milestone['Progress (%)'];
              const milestoneProgressValue = milestoneProgress !== undefined && milestoneProgress !== null ? Math.round(milestoneProgress) : 0;
              doc.text(`${milestoneProgressValue}%`, 285, currentY + 9, { width: 33, align: 'center' });
              
              const fee = milestone['Fee Amount (KSh)'] || '0';
              const feeNum = typeof fee === 'string' ? parseFloat(fee.replace(/,/g, '')) : fee;
              doc.text(feeNum ? feeNum.toLocaleString() : '0', 323, currentY + 9, { width: 52, align: 'right' });
              
              const milestoneDuration = calculateDuration(milestone['Start Date'], milestone['Due Date'] || milestone['End Date']);
              doc.text(milestoneDuration, 380, currentY + 9, { width: 30, align: 'center' });
              doc.text(milestone['Start Date'] || 'N/A', 415, currentY + 9, { width: 38, align: 'center' });
              doc.text(milestone['Due Date'] || milestone['End Date'] || 'N/A', 458, currentY + 9, { width: 38, align: 'center' });
              doc.text(milestone['Assigned User'] || 'Unassigned', 501, currentY + 9, { width: 39, ellipsis: true });

              currentY += milestoneRowHeight;
            });
          }
        });
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

export function generateMilestonesPDF(data: any, filename: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true, autoFirstPage: false });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      let pageNumber = 0;
      const addNewPage = () => { doc.addPage(); pageNumber++; addHeader(); addFooter(); return 120; };
      const addHeader = () => {
        const logoPath = path.join(__dirname, '../../Appkings.png');
        if (fs.existsSync(logoPath)) doc.image(logoPath, 40, 30, { width: 40 });
        doc.fontSize(18).fillColor('#1F4E79').font('Helvetica-Bold').text('Milestones Report', 90, 35);
        doc.fontSize(8).fillColor('#666666').font('Helvetica').text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 90, 55);
        doc.moveTo(40, 80).lineTo(555, 80).strokeColor('#4472C4').lineWidth(1).stroke();
      };
      const addFooter = () => {
        doc.fontSize(8).fillColor('#999999').font('Helvetica').text(`Page ${pageNumber} - Generated by TaskFlow System`, 40, 770, { align: 'center', width: 515 });
      };

      let currentY = addNewPage();
      const milestones = Array.isArray(data) ? data : [];
      
      // Table headers
      const tableHeaders = ['Project', 'Milestone Name', 'Manager', 'Progress', 'Billing Status', 'Fee (KSh)', 'Start Date', 'Due Date'];
      const colWidths = [80, 100, 80, 50, 70, 60, 60, 60];
      const tableWidth = colWidths.reduce((sum, width) => sum + width, 0);
      const startX = 40;
      
      // Draw table header
      doc.rect(startX, currentY, tableWidth, 25).fillAndStroke('#E8E8E8', '#AAAAAA');
      let xPos = startX;
      tableHeaders.forEach((header, i) => {
        doc.fillColor('#1a1a1a').fontSize(8).font('Helvetica-Bold');
        doc.text(header, xPos + 3, currentY + 8, { width: colWidths[i] - 6, ellipsis: true });
        xPos += colWidths[i];
      });
      currentY += 25;
      
      // Draw table rows
      milestones.forEach((milestone: any, index: number) => {
        if (currentY + 20 > 750) currentY = addNewPage();
        
        const rowBg = index % 2 === 0 ? '#FFFFFF' : '#F8F8F8';
        doc.rect(startX, currentY, tableWidth, 20).fillAndStroke(rowBg, '#E5E5E5').lineWidth(0.5);
        
        xPos = startX;
        const rowData = [
          milestone['Project Name'] || 'N/A',
          milestone['Milestone Name'] || 'N/A',
          milestone['Manager'] || 'Not assigned',
          `${milestone['Progress (%)'] || 0}%`,
          milestone['Billing Status'] || 'none',
          milestone['Fee Amount (KSh)'] || '0',
          milestone['Start Date'] || 'N/A',
          milestone['Due Date'] || 'N/A'
        ];
        
        rowData.forEach((cellData, i) => {
          doc.fillColor('#2C2C2C').fontSize(7).font('Helvetica');
          doc.text(String(cellData), xPos + 3, currentY + 6, { width: colWidths[i] - 6, ellipsis: true });
          xPos += colWidths[i];
        });
        currentY += 20;
      });
      
      doc.end();
    } catch (error) { reject(error); }
  });
}

export function generatePerformancePDF(data: any, filename: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true, autoFirstPage: false });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      let pageNumber = 0;
      const addNewPage = () => { doc.addPage(); pageNumber++; addHeader(); addFooter(); return 120; };
      const addHeader = () => {
        const logoPath = path.join(__dirname, '../../Appkings.png');
        if (fs.existsSync(logoPath)) doc.image(logoPath, 40, 30, { width: 40 });
        doc.fontSize(18).fillColor('#1F4E79').font('Helvetica-Bold').text('Team Performance Report', 90, 35);
        doc.fontSize(8).fillColor('#666666').font('Helvetica').text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 90, 55);
        doc.moveTo(40, 80).lineTo(555, 80).strokeColor('#4472C4').lineWidth(1).stroke();
      };
      const addFooter = () => {
        doc.fontSize(8).fillColor('#999999').font('Helvetica').text(`Page ${pageNumber} - Generated by TaskFlow System`, 40, 770, { align: 'center', width: 515 });
      };

      let currentY = addNewPage();
      const performance = Array.isArray(data) ? data : [];
      
      // Table headers
      const tableHeaders = ['Team Member', 'Total Tasks', 'Completed', 'Completion Rate', 'Overdue Tasks', 'Avg Days/Task'];
      const colWidths = [120, 70, 70, 80, 80, 95];
      const tableWidth = colWidths.reduce((sum, width) => sum + width, 0);
      const startX = 40;
      
      // Draw table header
      doc.rect(startX, currentY, tableWidth, 25).fillAndStroke('#E8E8E8', '#AAAAAA');
      let xPos = startX;
      tableHeaders.forEach((header, i) => {
        doc.fillColor('#1a1a1a').fontSize(8).font('Helvetica-Bold');
        doc.text(header, xPos + 3, currentY + 8, { width: colWidths[i] - 6, ellipsis: true });
        xPos += colWidths[i];
      });
      currentY += 25;
      
      // Draw table rows
      performance.forEach((member: any, index: number) => {
        if (currentY + 20 > 750) currentY = addNewPage();
        
        const rowBg = index % 2 === 0 ? '#FFFFFF' : '#F8F8F8';
        doc.rect(startX, currentY, tableWidth, 20).fillAndStroke(rowBg, '#E5E5E5').lineWidth(0.5);
        
        xPos = startX;
        const rowData = [
          member['Team Member'] || 'N/A',
          member['Total Tasks'] || '0',
          member['Completed Tasks'] || '0',
          `${member['Completion Rate (%)'] || 0}%`,
          member['Overdue Tasks'] || '0',
          member['Average Days per Task'] || '0'
        ];
        
        rowData.forEach((cellData, i) => {
          doc.fillColor('#2C2C2C').fontSize(7).font('Helvetica');
          doc.text(String(cellData), xPos + 3, currentY + 6, { width: colWidths[i] - 6, ellipsis: true });
          xPos += colWidths[i];
        });
        currentY += 20;
      });
      
      doc.end();
    } catch (error) { reject(error); }
  });
}

export function generateWorkloadPDF(data: any, filename: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true, autoFirstPage: false });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      let pageNumber = 0;
      const addNewPage = () => { doc.addPage(); pageNumber++; addHeader(); addFooter(); return 120; };
      const addHeader = () => {
        const logoPath = path.join(__dirname, '../../Appkings.png');
        if (fs.existsSync(logoPath)) doc.image(logoPath, 40, 30, { width: 40 });
        doc.fontSize(18).fillColor('#1F4E79').font('Helvetica-Bold').text('Workload Analysis Report', 90, 35);
        doc.fontSize(8).fillColor('#666666').font('Helvetica').text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 90, 55);
        doc.moveTo(40, 80).lineTo(555, 80).strokeColor('#4472C4').lineWidth(1).stroke();
      };
      const addFooter = () => {
        doc.fontSize(8).fillColor('#999999').font('Helvetica').text(`Page ${pageNumber} - Generated by TaskFlow System`, 40, 770, { align: 'center', width: 515 });
      };

      let currentY = addNewPage();
      const workload = Array.isArray(data) ? data : [];
      
      // Table headers
      const tableHeaders = ['Team', 'Members', 'Total Tasks', 'Avg Workload', 'Capacity', 'Utilization'];
      const colWidths = [120, 70, 80, 80, 80, 85];
      const tableWidth = colWidths.reduce((sum, width) => sum + width, 0);
      const startX = 40;
      
      // Draw table header
      doc.rect(startX, currentY, tableWidth, 25).fillAndStroke('#E8E8E8', '#AAAAAA');
      let xPos = startX;
      tableHeaders.forEach((header, i) => {
        doc.fillColor('#1a1a1a').fontSize(8).font('Helvetica-Bold');
        doc.text(header, xPos + 3, currentY + 8, { width: colWidths[i] - 6, ellipsis: true });
        xPos += colWidths[i];
      });
      currentY += 25;
      
      // Draw table rows
      workload.forEach((team: any, index: number) => {
        if (currentY + 20 > 750) currentY = addNewPage();
        
        const rowBg = index % 2 === 0 ? '#FFFFFF' : '#F8F8F8';
        doc.rect(startX, currentY, tableWidth, 20).fillAndStroke(rowBg, '#E5E5E5').lineWidth(0.5);
        
        xPos = startX;
        const rowData = [
          team['Team'] || 'N/A',
          team['Team Members'] || '0',
          team['Total Tasks'] || '0',
          team['Average Workload'] || '0',
          `${team['Team Capacity'] || 0}%`,
          `${team['Utilization Rate'] || 0}%`
        ];
        
        rowData.forEach((cellData, i) => {
          doc.fillColor('#2C2C2C').fontSize(7).font('Helvetica');
          doc.text(String(cellData), xPos + 3, currentY + 6, { width: colWidths[i] - 6, ellipsis: true });
          xPos += colWidths[i];
        });
        currentY += 20;
      });
      
      doc.end();
    } catch (error) { reject(error); }
  });
}

export function generateFinancialPDF(data: any, filename: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true, autoFirstPage: false });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      let pageNumber = 0;
      const addNewPage = () => { doc.addPage(); pageNumber++; addHeader(); addFooter(); return 120; };
      const addHeader = () => {
        const logoPath = path.join(__dirname, '../../Appkings.png');
        if (fs.existsSync(logoPath)) doc.image(logoPath, 40, 30, { width: 40 });
        doc.fontSize(18).fillColor('#1F4E79').font('Helvetica-Bold').text('Financial Report', 90, 35);
        doc.fontSize(8).fillColor('#666666').font('Helvetica').text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 90, 55);
        doc.moveTo(40, 80).lineTo(555, 80).strokeColor('#4472C4').lineWidth(1).stroke();
      };
      const addFooter = () => {
        doc.fontSize(8).fillColor('#999999').font('Helvetica').text(`Page ${pageNumber} - Generated by TaskFlow System`, 40, 770, { align: 'center', width: 515 });
      };

      let currentY = addNewPage();
      const financial = Array.isArray(data.financial) ? data.financial : (Array.isArray(data) ? data : []);
      
      // Table headers
      const tableHeaders = ['Project Name', 'Client', 'Status', 'Total Value', 'Paid Amount', 'Outstanding', 'Payment %'];
      const colWidths = [100, 80, 60, 75, 75, 75, 50];
      const tableWidth = colWidths.reduce((sum, width) => sum + width, 0);
      const startX = 40;
      
      // Draw table header
      doc.rect(startX, currentY, tableWidth, 25).fillAndStroke('#E8E8E8', '#AAAAAA');
      let xPos = startX;
      tableHeaders.forEach((header, i) => {
        doc.fillColor('#1a1a1a').fontSize(8).font('Helvetica-Bold');
        doc.text(header, xPos + 3, currentY + 8, { width: colWidths[i] - 6, ellipsis: true });
        xPos += colWidths[i];
      });
      currentY += 25;
      
      // Draw table rows
      financial.forEach((project: any, index: number) => {
        if (currentY + 20 > 750) currentY = addNewPage();
        
        const rowBg = index % 2 === 0 ? '#FFFFFF' : '#F8F8F8';
        doc.rect(startX, currentY, tableWidth, 20).fillAndStroke(rowBg, '#E5E5E5').lineWidth(0.5);
        
        xPos = startX;
        const rowData = [
          project['Project Name'] || 'N/A',
          project['Client'] || 'N/A',
          project['Project Status'] || 'N/A',
          `KSh ${project['Total Project Value (KSh)'] || 0}`,
          `KSh ${project['Paid Amount (KSh)'] || 0}`,
          `KSh ${project['Outstanding (KSh)'] || 0}`,
          `${project['Payment Completion (%)'] || 0}%`
        ];
        
        rowData.forEach((cellData, i) => {
          doc.fillColor('#2C2C2C').fontSize(7).font('Helvetica');
          doc.text(String(cellData), xPos + 3, currentY + 6, { width: colWidths[i] - 6, ellipsis: true });
          xPos += colWidths[i];
        });
        currentY += 20;
      });
      
      doc.end();
    } catch (error) { reject(error); }
  });
}

export function generateCompletePDF(data: any, filename: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true, autoFirstPage: false });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      let pageNumber = 0;
      const addNewPage = () => { doc.addPage(); pageNumber++; addHeader(); addFooter(); return 130; };
      const addHeader = () => {
        const logoPath = path.join(__dirname, '../../Appkings.png');
        if (fs.existsSync(logoPath)) doc.image(logoPath, 50, 40, { width: 50 });
        doc.fontSize(20).fillColor('#1F4E79').font('Helvetica-Bold').text('Complete Report', 120, 50, { align: 'left' });
        doc.fontSize(9).fillColor('#666666').font('Helvetica').text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 120, 75, { align: 'left' });
        doc.moveTo(50, 105).lineTo(545, 105).strokeColor('#4472C4').lineWidth(2).stroke();
      };
      const addFooter = () => {
        doc.fontSize(8).fillColor('#999999').font('Helvetica').text(`Page ${pageNumber} - Generated by TaskFlow System`, 50, 770, { align: 'center', width: 495 });
      };

      let currentY = addNewPage();
      
      // Add summary section
      doc.fontSize(14).fillColor('#1F4E79').font('Helvetica-Bold').text('Executive Summary', 50, currentY);
      currentY += 30;
      
      const projects = data.projects || [];
      const milestones = data.milestones || [];
      const performance = data.performance || [];
      
      doc.fontSize(10).fillColor('#000000').font('Helvetica');
      doc.text(`Total Projects: ${projects.length}`, 50, currentY);
      doc.text(`Total Milestones: ${milestones.length}`, 200, currentY);
      doc.text(`Team Members: ${performance.length}`, 350, currentY);
      currentY += 40;
      
      // Add projects section
      if (projects.length > 0) {
        doc.fontSize(12).fillColor('#1F4E79').font('Helvetica-Bold').text('Projects Overview', 50, currentY);
        currentY += 25;
        
        projects.slice(0, 10).forEach((project: any) => {
          if (currentY + 30 > 720) currentY = addNewPage();
          doc.fontSize(9).fillColor('#000000').font('Helvetica');
          doc.text(`• ${project['Project Name'] || 'N/A'} - ${project['Status'] || 'N/A'} (${project['Progress (%)'] || 0}%)`, 58, currentY);
          currentY += 15;
        });
        currentY += 20;
      }
      
      doc.end();
    } catch (error) { reject(error); }
  });
}

export async function generatePDFBuffer(options: PDFExportOptions): Promise<Buffer> {
  const { data, reportType, filename } = options;
  
  switch (reportType) {
    case 'projects':
      return generateProjectSummaryPDF(data, filename);
    case 'milestones':
      return generateMilestonesPDF(data, filename);
    case 'performance':
      return generatePerformancePDF(data, filename);
    case 'workload':
      return generateWorkloadPDF(data, filename);
    case 'financial':
      return generateFinancialPDF(data, filename);
    case 'complete':
      return generateCompletePDF(data, filename);
    default:
      throw new Error(`PDF generation not implemented for report type: ${reportType}`);
  }
}
